name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta todos los días a medianoche (UTC)
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Seany-Aguilar
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate pacman contribution graph"
          add: 'output/*.svg'
